import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Shirt, Users } from "lucide-react";
import runway from "../assets/runway,new.png";
import { CarouselControls } from "../components/CarouselControls";
import { useGameLogic } from "../hooks/useGameLogic";
const GamePage = ({ tops, bottoms }) => {
    const { selectedSkin, setSelectedSkin, currentTop, currentBottom, saveStatus, user, handlers } = useGameLogic(tops, bottoms);
    return (_jsx("div", { className: "min-h-screen w-full flex items-center justify-center bg-cover bg-center px-2 py-2", style: { backgroundImage: `url(${runway})` }, children: _jsxs("div", { className: "relative w-full max-w-6xl h-[400px] md:h-[520px] flex items-center justify-center", children: [_jsxs("div", { className: "absolute left-0 flex flex-col space-y-1 md:space-y-4 z-20", children: [_jsx(CarouselControls, { onClickPrev: handlers.prevTop, onClickNext: handlers.nextTop, icon: _jsx(Shirt, {}), title: "TOP", currentName: currentTop?.name || "Ingen" }), _jsx(CarouselControls, { onClickPrev: handlers.prevBottom, onClickNext: handlers.nextBottom, icon: _jsx(Users, {}), title: "BOTTOM", currentName: currentBottom?.name || "Ingen" }), _jsxs("div", { className: "mt-2 md:mt-4", children: [_jsx("button", { onClick: handlers.handleSaveOutfit, disabled: !user || !currentTop || !currentBottom || saveStatus === "saving", className: `px-4 py-2 rounded text-white text-xs md:text-base ${!user ? "bg-gray-400" : "bg-green-500 hover:bg-green-600"}`, children: saveStatus === "saving" ? "Saving..." : "Save outfit" }), !user && _jsx("p", { className: "text-[9px] text-red-200", children: "Log in to save." })] })] }), _jsxs("div", { className: "relative w-[180px] h-[270px] md:w-[400px] md:h-[600px] z-10", children: [currentBottom && _jsx("img", { src: currentBottom.image, className: "absolute inset-0 w-full h-full object-contain", alt: "Bottom" }), currentTop && _jsx("img", { src: currentTop.image, className: "absolute inset-0 w-full h-full object-contain z-10", alt: "Top" })] }), _jsx("div", { className: "absolute right-0 flex flex-col space-y-2 z-20", children: ["dark", "light"].map((skin) => (_jsxs("button", { onClick: () => setSelectedSkin(skin), disabled: selectedSkin === skin, className: `px-4 py-2 rounded text-white text-xs md:text-base ${selectedSkin === skin ? "bg-gray-400" : "bg-indigo-500 hover:bg-indigo-600"}`, children: [skin.charAt(0).toUpperCase() + skin.slice(1), " skin"] }, skin))) })] }) }));
};
export default GamePage;
