import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useContext } from "react";
import { AuthContext } from "../contexts/AuthContext";
import runway from "../assets/runway,new.png";
function HomePage() {
    useContext(AuthContext);
    return (_jsx("div", { className: "min-h-screen w-full flex items-center justify-center\r\n             bg-cover bg-center md:bg-no-repeat md:bg-bottom px-2 py-4 md:px-0 md:py-0", style: {
            backgroundImage: `url(${runway})`,
            backgroundSize: "cover",
        }, children: _jsxs("div", { className: "rounded-xl md:rounded-2xl shadow-2xl shadow-black p-4 md:p-10 w-full max-w-3xl flex flex-col gap-3 md:gap-5 mt-4 md:mt-20", style: {
                backgroundColor: "rgba(31, 41, 55, 0.4)",
                backdropFilter: "blur(10px)",
            }, children: [_jsxs("div", { className: "flex flex-col items-center justify-center w-full mt-4 md:mt-8", children: [_jsx("h1", { className: "text-6xl md:text-5xl lg:text-7xl font-light text-white font-italiana tracking-widest ", children: "Top model" }), _jsx("h2", { className: "text-lg md:text-2xl text-white font-italiana italic transform translate-x-12 md:translate-x-27 -mt-1", children: "Dress Up" })] }), _jsx("div", { className: "mt-10" }), _jsx("p", { className: "text-gray-200 leading-relaxed mb-3 md:mb-6 text-xs md:text-base", children: "Let your imagination run wild and create your own unique outfits by mixing and matching clothes. The game is designed for anyone who loves fashion, styling, or just wants to have fun while designing unique looks." }), _jsx("h2", { className: "text-sm md:text-xl lg:text-2xl font-light text-white mb-2 md:mb-4", children: " How does the game work?" }), _jsxs("div", { className: "space-y-2 md:space-y-4 text-gray-200 text-xs md:text-base", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-xs md:text-lg lg:text-xl font-medium text-white", children: "Choose a character" }), _jsx("p", { className: "leading-relaxed", children: "Select the model you want to style in the game." })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-xs md:text-lg lg:text-xl font-medium text-white", children: " Explore the wardrobe" }), _jsx("p", { className: "leading-relaxed", children: "Browse through tops and bottoms. Each category contains a variety of outfits to choose from." })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-xs md:text-xl font-medium text-white", children: "Scroll through to dress up" }), _jsx("p", { className: "leading-relaxed", children: "Browse the clothing items to put them on your model. You can change and adjust as much as you like until you find the perfect style." })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-xs md:text-xl font-medium text-white", children: "Save your look" }), _jsx("p", { className: "leading-relaxed", children: "Once you\u2019re happy, you can save your outfit or start over to create an entirely new style. You can later find your creations on your profile page." })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-xs md:text-xl font-medium text-white", children: "Rate other models" }), _jsx("p", { className: "leading-relaxed", children: "After creating the perfect look, it\u2019s ready to be rated by other users. You can also rate other users\u2019 outfits by giving them 1\u20135 stars." })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-xs md:text-xl font-medium text-white", children: "Let your creativity flow" }), _jsx("p", { className: "leading-relaxed", children: "Let your creativity flow and see what unique styles you can create!" })] })] })] }) }));
}
export default HomePage;
