import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// src/page/ProfilePage.tsx
import { useState } from "react";
import backstage from "../assets/backstage.png";
import { EyeIcon, EyeSlashIcon } from "@heroicons/react/24/outline";
import LoadingSpinner from "../components/LoadingSpinner";
import { useProfile } from "../hooks/useProfile";
import { findClothingItem } from "../utils/clothingUtils";
function ProfilePage() {
    const [showPassword, setShowPassword] = useState(false);
    const { profileData, setProfileData, password, setPassword, message, outfits, outfitsLoading, loading, handleSave } = useProfile();
    if (loading)
        return _jsx(LoadingSpinner, {});
    return (_jsxs("div", { className: "relative min-h-screen w-full", children: [_jsx("div", { className: "absolute inset-0 bg-cover bg-center z-0", style: { backgroundImage: `url(${backstage})` } }), _jsxs("div", { className: "relative z-10 flex flex-row items-center justify-center min-h-screen p-2 md:p-0 gap-2 md:gap-8 flex-wrap", children: [_jsx("h1", { className: "absolute top-20 left-1/2 -translate-x-1/2 text-lg md:text-4xl lg:text-6xl text-amber-50 whitespace-nowrap md:top-0 md:mt-30", children: "YOUR PROFILE PAGE" }), _jsxs("div", { className: "mt-30 md:mt-10 flex w-full max-w-[280px] flex-col rounded-2xl bg-purple-300/90 p-4 shadow-2xl sm:max-w-xs md:max-w-sm md:p-7", children: [_jsx("label", { className: "ml-2 text-xs md:text-sm font-semibold", children: "Username" }), _jsx("input", { value: profileData.username, readOnly: true, className: "w-full border px-4 py-2 rounded-xl text-gray-500 bg-gray-100 cursor-not-allowed mb-3" }), _jsx("label", { className: "ml-2 text-xs md:text-sm font-semibold", children: "Email" }), _jsx("input", { value: profileData.email, onChange: (e) => setProfileData({ ...profileData, email: e.target.value }), className: "w-full border px-4 py-2 rounded-xl mb-3" }), _jsx("label", { className: "ml-2 text-xs md:text-sm font-semibold", children: "Phone number" }), _jsx("input", { value: profileData.phone, onChange: (e) => setProfileData({ ...profileData, phone: e.target.value }), className: "w-full border px-4 py-2 rounded-xl mb-3" }), _jsx("label", { className: "ml-2 text-xs md:text-sm font-semibold", children: "Password" }), _jsxs("div", { className: "relative", children: [_jsx("input", { type: showPassword ? "text" : "password", value: password, onChange: (e) => setPassword(e.target.value), className: "w-full border px-4 py-2 rounded-xl pr-10" }), _jsx("span", { className: "absolute right-3 top-1/2 -translate-y-1/2 cursor-pointer", onClick: () => setShowPassword(!showPassword), children: showPassword ? _jsx(EyeSlashIcon, { className: "h-5 w-5" }) : _jsx(EyeIcon, { className: "h-5 w-5" }) })] }), _jsx("button", { onClick: handleSave, className: "bg-purple-900 mt-5 rounded-xl py-2 text-amber-50 hover:bg-purple-800 transition", children: "Save" }), message && _jsx("p", { className: "text-center text-purple-900 font-bold mt-3 text-sm", children: message })] }), _jsxs("div", { className: "mt-10 flex w-full max-w-[280px] flex-col rounded-2xl bg-purple-300/90 p-4 shadow-2xl sm:max-w-xs md:max-w-sm md:p-7", children: [_jsx("h2", { className: "text-xl font-bold text-center text-purple-900", children: "Saved Outfits" }), outfitsLoading ? (_jsx("p", { className: "text-center", children: "Loading outfits..." })) : outfits.length === 0 ? (_jsx("p", { className: "text-center", children: "No saved outfits" })) : (_jsx("div", { className: "flex flex-col gap-4 max-h-[500px] overflow-y-auto pr-2", children: outfits.map((outfit) => {
                                    const topItem = findClothingItem(outfit.top_id, "top", outfit.skin);
                                    const bottomItem = findClothingItem(outfit.bottom_id, "bottom", outfit.skin);
                                    return (_jsxs("div", { className: "bg-white/80 p-4 rounded-xl border-2 border-purple-700", children: [_jsxs("div", { className: "relative w-full h-32 md:h-40", children: [bottomItem && _jsx("img", { src: bottomItem.image, className: "absolute inset-0 w-full h-full object-contain" }), topItem && _jsx("img", { src: topItem.image, className: "absolute inset-0 w-full h-full object-contain" })] }), _jsxs("div", { className: "mt-2 text-xs text-gray-700", children: [_jsxs("p", { children: [_jsx("strong", { children: "Top:" }), " ", topItem ? topItem.name : "Unknown Top"] }), _jsxs("p", { children: [_jsx("strong", { children: "Bottom:" }), " ", bottomItem ? bottomItem.name : "Unknown Bottom"] })] })] }, outfit._id));
                                }) }))] })] })] }));
}
export default ProfilePage;
