import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import MyTextInput from "../components/MyTextInput";
import runway from "../assets/runway,new.png";
import gubbeImage from "../assets/gröngala.png";
import gubbeImage1 from "../assets/Bluedress.png";
import { useSignup } from "../hooks/useSignup";
function SignupPage() {
    const { formData, errorMessage, isLoading, usernameStatus, updateField, checkUsername, submitRegister } = useSignup();
    return (_jsxs("div", { className: "min-h-screen w-full flex items-center justify-center bg-cover bg-center px-2 py-4", style: { backgroundImage: `url(${runway})` }, children: [_jsxs("div", { className: "rounded-xl md:rounded-2xl shadow-2xl p-6 w-full max-w-xs md:max-w-sm flex flex-col gap-3", style: { backgroundColor: "rgba(31, 41, 55, 0.4)", backdropFilter: "blur(10px)" }, children: [_jsx("h1", { className: "text-xl md:text-3xl font-light text-center mb-4 text-white tracking-wider", children: "Create account" }), _jsxs("div", { className: "flex flex-col gap-1", children: [_jsx("label", { className: "text-gray-300 text-sm", children: "Username" }), _jsx(MyTextInput, { value: formData.username, onChange: (e) => updateField("username", e.target.value), onBlur: () => checkUsername(formData.username), className: "border-b border-gray-500 bg-gray-700 bg-opacity-20 text-white rounded-full px-3 py-2 md:px-5 md:py-3 text-sm md:text-base focus:outline-none focus:border-white transition-all duration-300 placeholder-gray-400", placeholder: "Username" }), usernameStatus === "checking" && _jsx("p", { className: "text-[10px] text-gray-300", children: "Checking..." }), usernameStatus === "available" && _jsx("p", { className: "text-[10px] text-green-500", children: "Available!" }), usernameStatus === "taken" && _jsx("p", { className: "text-[10px] text-red-500", children: "Taken" })] }), ["phone", "email", "password"].map((field) => (_jsxs("div", { className: "flex flex-col gap-1", children: [_jsx("label", { className: "text-amber-50 text-sm capitalize", children: field }), _jsx(MyTextInput, { type: field === "password" ? "password" : "text", value: formData[field], onChange: (e) => updateField(field, e.target.value), className: "border-b border-gray-500 bg-gray-700 bg-opacity-20 text-white rounded-full px-3 py-2 md:px-5 md:py-3 text-sm md:text-base focus:outline-none focus:border-white transition-all duration-300 placeholder-gray-400", placeholder: field.charAt(0).toUpperCase() + field.slice(1) })] }, field))), errorMessage && (_jsx("p", { className: "text-red-400 text-xs text-center bg-red-500/10 py-2 rounded", children: errorMessage })), _jsx("button", { onClick: submitRegister, disabled: isLoading, className: "w-full bg-white/10 hover:bg-white/20 text-white font-semibold py-3 rounded-full border border-gray-500 transition-all mt-4", children: isLoading ? "Creating account..." : "Sign up" })] }), _jsxs("div", { className: "hidden md:flex items-center ml-4", children: [_jsx("img", { src: gubbeImage, alt: "Gubbe", className: "w-80 h-auto" }), _jsx("img", { src: gubbeImage1, alt: "Gubbe", className: "w-80 h-auto -ml-32" })] })] }));
}
export default SignupPage;
